### ISSUE TITLE
ADB isn't working.

### ISSUE THREAD

**Issue by honey-roasted** [senkkou/E7AutoBuy#1]
Hi, I am following the instructions, but when I am trying to get it to run it crashes after I enter amount of refreshes. This is what I am getting from the crash.log file. I have followed the instructions and have tried redownloading everything and enabling adb, but I still come across the same issue. What can I do about this?
ADB isn't working.
Traceback (most recent call last):
  File "autobuy.py", line 125, in <module>
  File "autobuy.py", line 22, in screen
  File "PIL\Image.py", line 3023, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000029FB0AE8720>

**Comment by senkkou** [comment]
Which emulator are you using ? Can you try LDplayer ?
Since you said you are following the instructions i will assume you already enabled adb in whichever emulator you are using. Try with LDPlayer. I saw some problems with adb on bluestacks before.

**Comment by Glxtchless** [comment]
Im getting the same issue. Im using Google Play for PC (Beta). I searched for any way to enable ADB but i couldnt find one, as its not in the emulator, even in the advanced tab.

**Comment by senkkou** [comment]
> Im getting the same issue. Im using Google Play for PC (Beta). I searched for any way to enable ADB but i couldnt find one, as its not in the emulator, even in the advanced tab.

It is an emulator, but currently you cant enable adb in a standard way on it. Use another emulator that supports adb, like LDplayer.

**Comment by honey-roasted** [comment]
It is working on ldplayer now, but it doesn't buy any bookmarks. Is there anything I can do about this.

**Comment by senkkou** [comment]
> It is working on ldplayer now, but it doesn't buy any bookmarks. Is there anything I can do about this.

Is your game in English ?

**Comment by honey-roasted** [comment]
Yes

**Comment by senkkou** [comment]
> Yes

Are you using 16:9 resolution ?
And remember de enter the shop and leave the screen all scrolled to the top. Then dont touch the screen anymore after that and start the program.

**Comment by honey-roasted** [comment]
> > Yes
> 
> Are you using 16:9 resolution ? And remember de enter the shop and leave the screen all scrolled to the top. Then dont touch the screen anymore after that and start the program.

Thank you
